[package]
name = "venix_macros"
version = "1.0.2"
edition = "2024"
description = "helper crate for macros for venix ecs"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ArjitSinghLodhi/Venix_macros"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.4"
